---
apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
  labels:
    toolkit.fluxcd.io/tenant: sre-team

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: default
spec:
  interval: 24h
  url: https://charts.bitnami.com/bitnami

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 8.8.*
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: default
      interval: 12h
  values:
    provider: pihole
    extraArgs:
      pihole-api-version: 6
    policy: upsert-only
    txtOwnerId: "homelab"
    pihole:
      server: http://pihole.home
    extraEnvVars:
      - name: EXTERNAL_DNS_PIHOLE_PASSWORD
        # TODO: fix this
        value: admin
    serviceAccount:
      create: true
      name: "external-dns"
    ingressClassFilters:
      - nginx-internal

    logLevel: debug
