---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-system
  labels:
    toolkit.fluxcd.io/tenant: sre-team

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: nginx-system
spec:
  interval: 24h
  url: https://kubernetes.github.io/ingress-nginx

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: nginx-system
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.12.*"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: nginx-system
      interval: 12h
