apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/capacitor
  - ../base/homepage
# patches:
#   - path: podinfo-values.yaml
#     target:
#       kind: HelmRelease
